name: CREATE-env
channels:
  - bioconda
  - conda-forge
  - r
dependencies:
  - nextflow
  - ffq==0.3.1
  - samtools==1.18
  - bedtools==2.31.1
  - gffread==0.12.7
  - gtfsort==0.2.2
  - fastqc==0.12.1
  - multiqc==1.19
  - trim-galore==0.6.10
  - chopper==0.9.0
  - minimap2==2.26
  - salmon==1.10.1
  - alevin-fry=0.10.0
  - star==2.7.11a
  - seqtk==1.4
  - flair==2.0.0
  - time
  - pigz
  - r-base==4.2.3
  - r-devtools
  - r-tidyr
  - r-dplyr
  - r-readr
  - r-stringr
  - r-remotes
  - r-qqman
  - r-ggplot2
  - r-ggforce
  - r-ggupset
  - r-ggrepel
  - r-ggdist
  - r-ggraph
  - r-ggh4x
  - r-ggbump
  - r-ggfortify
  - r-ggdag
  - r-ggridges
  - r-gggenes
  - r-ggpointdensity
  - r-ggdensity
  - r-ggcorrplot
  - r-ggmuller
  - r-ggpubr
  - r-ggsignif
  - r-ggsci
  - r-gganimate
  - r-ggthemes
  - r-patchwork
  - r-rcolorbrewer
  - r-argparse
  - r-import
  - r-Matrix
  - r-reticulate
  - r-languageserver
  - r-seurat
  - r-seuratdisk
  - r-metap
  - r-signac
  - r-velocyto.r
  - pwwang::r-seuratwrappers
  - bioconductor-BiocIO
  - bioconductor-Biostrings
  - bioconductor-GenomicFeatures
  - bioconductor-SummarizedExperiment
  - bioconductor-SingleCellExperiment
  - bioconductor-HDF5Array
  - bioconductor-DESeq2
  - bioconductor-tximeta
  - bioconductor-tximport
  - bioconductor-eisaR
  - bioconductor-pcaMethods
  - bioconductor-multtest
  - bioconductor-scp
  - bioconductor-scater
  - bioconductor-scuttle
  - bioconductor-scran
  - bioconductor-scrnaseq
  - bioconductor-fishpond
  - bioconductor-velociraptor
  - bioconductor-bsgenome
  - bioconductor-decipher
  - bioconductor-drimseq
  - bioconductor-stager
  - python==3.10.13
  - pip
  - tqdm
  - ncls
  - rpy2
  - mappy
  - numpy
  - pysam
  - pandas
  - seaborn
  - cutadapt
  - biopython
  - matplotlib
  - pybedtools
  - pip:
    - fasta_digest
